version: "3.1"

services:
  base_postgres:
    image: postgres:15.3
    container_name: base_postgres
    restart: always
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 9002:5432
    networks:
      - postgres

  minio:
      image: minio/minio:RELEASE.2024-10-13T13-34-11Z
      container_name: minio
      environment:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: 12345678
      volumes:
          - ./minio/minio_data:/data
      ports:
          - 9000:9000
          - 9001:9001
      command: server --console-address ":9001" /data

  base_pgadmin:
      image: dpage/pgadmin4:7.8
      container_name: base_pgadmin
      environment:
          - PGADMIN_DEFAULT_EMAIL=ya@ya.ru
          - PGADMIN_DEFAULT_PASSWORD=1234
      volumes:
          - ./pgadmin:/var/lib/pgadmin
      ports:
          - 9003:80
      restart: unless-stopped
      networks:
          - postgres

networks:
  postgres:
    name: bridge-mock-shop
    driver: bridge

volumes:
  postgres:
  minio_data:
  pgadmin:


